### ISSUE TITLE
why not pulseaudio ?

### ISSUE THREAD

**Issue by KenN7** [parastuffs/splitnmerge-audio#1]
Maybe this fixes your prob ?
https://askubuntu.com/questions/421014/share-an-audio-playback-stream-through-a-live-audio-video-conversation-like-sk

**Comment by parastuffs** [comment]
Nice, j'ajoute la référence dans mon pipeline.
C'est similaire à [ce post](https://phpboyscout.uk/adding-ambient-sounds-to-your-discord-server-on-linux/) que je dois encore analyser.

**Comment by KenN7** [comment]
Ah ouais, même chose que ton post :+1:
